<div class="alert alert-block alert-info">
<center> <h1> WORLD HAPPINESS </h1> </center> <br>
<center> <h2> Data Visualization </h2> </center> <br>
<center> <h3> 2023 </h3> </center> <br>

**Table of Contents** <br>
* [1. Initial Setup](#setup)
    * [1.1. Import Libraries](#importlibraries)
    * [1.2. Import Data](#importdata)
* [2. Data Preparation](#datapreparation)

<hr>
<a class="anchor" id="setup">
    
# 1. Initial Setup
    
</a>

<a class="anchor" id="importlibraries">

## 1.1. Import Libraries

</a>

In [1]:
import pandas as pd
import pycountry_convert as pc

<a class="anchor" id="importdata">

## 1.2. Import Data

</a>

In [2]:
ds_2015 = pd.read_csv('2015.csv', sep=",")
ds_2016 = pd.read_csv('2016.csv', sep=",")
ds_2017 = pd.read_csv('2017.csv', sep=",")
ds_2018 = pd.read_csv('2018.csv', sep=",")
ds_2019 = pd.read_csv('2019.csv', sep=",")
ds_2020 = pd.read_excel('2020.xls')
ds_2021 = pd.read_excel('2021.xls')
ds_2022 = pd.read_csv('2022.csv', sep=",")
ds_2023 = pd.read_excel('2023.xls')

In [3]:
ds_2015.rename(columns = {'Economy (GDP per Capita)':'Economy','Health (Life Expectancy)':'Health','Trust (Government Corruption)':'Trust','Dystopia Residual':'Dystopia'}, inplace = True)
ds_2015.drop(columns=['Region'],inplace=True)

In [4]:
ds_2016.rename(columns = {'Economy (GDP per Capita)':'Economy','Health (Life Expectancy)':'Health','Trust (Government Corruption)':'Trust','Dystopia Residual':'Dystopia'}, inplace = True)
ds_2016.drop(columns=['Region'],inplace=True)

In [5]:
ds_2017.rename(columns = {'Happiness.Rank':'Happiness Rank','Happiness.Score':'Happiness Score',
                          'Economy..GDP.per.Capita.':'Economy','Health..Life.Expectancy.':'Health',
                         'Trust..Government.Corruption.':'Trust','Dystopia.Residual':'Dystopia'}, inplace = True)

In [6]:
ds_2018.rename(columns = {'Overall rank':'Happiness Rank','Score':'Happiness Score','Country or region':'Country',
                          'GDP per capita':'Economy','Healthy life expectancy':'Health',
                          'Social support':'Family','Freedom to make life choices':'Freedom',
                         'Perceptions of corruption':'Trust'}, inplace = True)

In [7]:
ds_2019.rename(columns = {'Overall rank':'Happiness Rank','Score':'Happiness Score','Country or region':'Country',
                          'GDP per capita':'Economy','Healthy life expectancy':'Health',
                          'Social support':'Family','Freedom to make life choices':'Freedom',
                         'Perceptions of corruption':'Trust'}, inplace = True)

In [8]:
ds_2020.rename(columns = {'Ladder score':'Happiness Score','Country name':'Country',
                          'Explained by: Log GDP per capita':'Economy','Explained by: Healthy life expectancy':'Health',
                          'Explained by: Social support':'Family','Explained by: Freedom to make life choices':'Freedom',
                         'Explained by: Perceptions of corruption':'Trust','Explained by: Generosity':'Generosity','Dystopia + residual':'Dystopia'}, inplace = True)
ds_2020.drop(columns=['Regional indicator'],inplace=True)
ds_2020['Happiness Rank']=ds_2020.index+1

In [9]:
ds_2021.rename(columns = {'Ladder score':'Happiness Score','Country name':'Country',
                          'Explained by: Log GDP per capita':'Economy','Explained by: Healthy life expectancy':'Health',
                          'Explained by: Social support':'Family','Explained by: Freedom to make life choices':'Freedom',
                         'Explained by: Perceptions of corruption':'Trust','Explained by: Generosity':'Generosity','Dystopia + residual':'Dystopia'}, inplace = True)
ds_2021.drop(columns=['Regional indicator'],inplace=True)
ds_2021['Happiness Rank']=ds_2021.index+1

In [10]:
ds_2022.rename(columns = {'RANK':'Happiness Rank','Happiness score':'Happiness Score',
                          'Explained by: GDP per capita':'Economy','Explained by: Healthy life expectancy':'Health',
                          'Explained by: Social support':'Family','Explained by: Freedom to make life choices':'Freedom',
                         'Explained by: Perceptions of corruption':'Trust','Explained by: Generosity':'Generosity'}, inplace = True)

In [11]:
ds_2023.rename(columns = {'Ladder score':'Happiness Score','Country name':'Country','Explained by: Log GDP per capita':'Economy','Explained by: Healthy life expectancy':'Health',
                          'Explained by: Social support':'Family','Explained by: Freedom to make life choices':'Freedom',
                         'Explained by: Perceptions of corruption':'Trust','Explained by: Generosity':'Generosity','Dystopia + residual':'Dystopia'}, inplace = True)
ds_2023['Happiness Rank']=ds_2023.index+1

<hr>
<a class="anchor" id="datapreparation">
    
# 2. Data Preparation
    
</a>

In [12]:
# Creating a column in each dataset with the respective year
ds_2015.insert(2, 'Year', 2015)
ds_2016.insert(2, 'Year', 2016)
ds_2017.insert(2, 'Year', 2017)
ds_2018.insert(2, 'Year', 2018)
ds_2019.insert(2, 'Year', 2019)
ds_2020.insert(2, 'Year', 2020)
ds_2021.insert(2, 'Year', 2021)
ds_2022.insert(2, 'Year', 2022)
ds_2023.insert(2, 'Year', 2023)

In [13]:
# Merging the datasets
ds = pd.concat([ds_2015, ds_2016, ds_2017, ds_2018, ds_2019,ds_2020,ds_2021,ds_2022,ds_2023])
ds

,Country,Happiness Rank,Year,Happiness Score,Economy,Family,Health,Freedom,Trust,Generosity,Dystopia
0,Switzerland,1,2015,7.5870,1.396510,1.349510,0.941430,0.665570,0.419780,0.296780,2.517380
1,Iceland,2,2015,7.5610,1.302320,1.402230,0.947840,0.628770,0.141450,0.436300,2.702010
2,Denmark,3,2015,7.5270,1.325480,1.360580,0.874640,0.649380,0.483570,0.341390,2.492040
3,Norway,4,2015,7.5220,1.459000,1.330950,0.885210,0.669730,0.365030,0.346990,2.465310
4,Canada,5,2015,7.4270,1.326290,1.322610,0.905630,0.632970,0.329570,0.458110,2.451760
...,...,...,...,...,...,...,...,...,...,...,...
132,Congo (Kinshasa),133,2023,3.2072,0.530779,0.783747,0.104758,0.375472,0.068287,0.182573,1.161580
133,Zimbabwe,134,2023,3.2035,0.758279,0.880513,0.068653,0.362508,0.117115,0.111627,0.904856
134,Sierra Leone,135,2023,3.1376,0.669699,0.540343,0.091811,0.370907,0.051077,0.192731,1.221006
135,Lebanon,136,2023,2.3922,1.416999,0.475936,0.398308,0.122771,0.027208,0.060824,-0.109798
136,Afghanistan,137,2023,1.8590,0.644600,0.000000,0.086704,0.000000,0.058644,0.092965,0.976065

In [14]:
countries=ds['Country']

In [15]:
def country_to_continent(country_name):
    country_alpha2 = pc.country_name_to_country_alpha2(country_name)
    country_alpha3=pc.country_name_to_country_alpha3(country_name)
    country_continent_code = pc.country_alpha2_to_continent_code(country_alpha2)
    country_continent_name = pc.convert_continent_code_to_continent_name(country_continent_code)
    return country_continent_name
def country_to_ISO3(country_name):
    country_alpha3=pc.country_name_to_country_alpha3(country_name)
    return country_alpha3

# Example
continent=[]
for i in countries:
    if i=='Kosovo':
        continent.append('Europe')
    elif i=='North Cyprus':
        continent.append('Europe')
    elif i=='Somaliland region':
        continent.append('Africa')
    elif i=='Palestinian Territories':
        continent.append('Asia')
    elif i=='Congo (Kinshasa)':
        continent.append('Africa')
    elif i=='Congo (Brazzaville)':
        continent.append('Africa')
    elif i=='Somaliland Region':
        continent.append('Africa')
    elif i=='Taiwan Province of China':
        continent.append('Asia')
    elif i=='Hong Kong S.A.R. of China':
        continent.append('Asia')
    elif i=='State of Palestine':
        continent.append('Asia')
    elif i=='Turkiye':
        continent.append('Europe')
    elif i=='Hong Kong S.A.R., China':
        continent.append('Asia')  
    elif i=='Trinidad & Tobago':
        continent.append('Central America')
    else:
        continent.append(country_to_continent(i))

codes=[]
for i in countries:
    if i=='Kosovo':
        codes.append('XXK')
    elif i=='North Cyprus':
        codes.append('CYP')
    elif i=='Somaliland region':
        codes.append('SOM')
    elif i=='Palestinian Territories':
        codes.append('PSE')
    elif i=='Congo (Kinshasa)':
        codes.append('COD')
    elif i=='Congo (Brazzaville)':
        codes.append('COG')
    elif i=='Somaliland Region':
        codes.append('SOM')
    elif i=='Taiwan Province of China':
        codes.append('TWN')
    elif i=='Hong Kong S.A.R. of China':
        codes.append('HKG')
    elif i=='State of Palestine':
        codes.append('PSE')
    elif i=='Turkiye':
        codes.append('TUR')
    elif i=='Hong Kong S.A.R., China':
        codes.append('HKG')  
    elif i=='Trinidad & Tobago':
        codes.append('TTO')
    else:
        codes.append(country_to_ISO3(i))

In [16]:
ds['Continent']=continent
ds['CountryCode']=codes

In [17]:
ds = ds.reindex(columns=['Year','Country','CountryCode', 'Continent','Happiness Rank','Happiness Score','Economy','Family','Health','Freedom',
                               'Generosity', 'Trust','Dystopia'])

In [18]:
dataset=ds.copy()

In [19]:
dataset.to_csv('dataset.csv',index=False)